name: Boot AGL with QEMU

description: Reusable workflow to boot QEMU with AGL image, supporting KVM if available.

inputs:
  KERNEL_IMAGE:
    description: Path to the kernel image (bzImage).
    required: true
  ROOTFS_IMAGE:
    description: Path to the root filesystem image.
    required: true
  TARGET_ARCH:
    description: Target machine architecture for QEMU (e.g., x86-64).
    required: true

runs:
  using: "composite"
  steps:
    - id: check-kvm-support
      name: Check KVM Support
      shell: bash
      run: |
        echo "Checking if KVM is supported..."
        if [[ -e /dev/kvm ]]; then
          echo "KVM is supported, installing KVM"
          sudo apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils virtinst virt-manager 
          echo "kvm=1" >> $GITHUB_OUTPUT
        else
          echo "KVM is not supported on this machine. QEMU will run in emulation mode."
          echo "kvm=0" >> $GITHUB_OUTPUT

    - name: Boot QEMU
      shell: bash
      env:
        KVM_SUPPORTED: ${{ steps.check-kvm-support.outputs.kvm }}
        TARGET_ARCH: ${{ inputs.TARGET_ARCH }}
      run: |
        if [ "$KVM_SUPPORTED" == "1" ]; then
          echo "KVM is supported. Launching QEMU with KVM acceleration."
          qemu-system-$TARGET_ARCH -m 4G \
            -kernel ${{ inputs.KERNEL_IMAGE }} \
            -drive file=${{ inputs.ROOTFS_IMAGE }},if=virtio,format=raw \
            -enable-kvm -cpu qemu64,+ssse3,+sse4.1,+sse4.2,+popcnt \
            -vga virtio \
            -device virtio-rng-pci \
            -serial mon:stdio -serial null \
            -net nic \
            -net user,hostfwd=tcp::2222-:22 \
            -nographic \
            -append "console=ttyS0 loglevel=7 root=/dev/vda"
        else
          echo "KVM is not supported. Launching QEMU in emulation mode."
          qemu-system-$TARGET_ARCH -m 4G \
            -kernel ${{ inputs.KERNEL_IMAGE }} \
            -drive file=${{ inputs.ROOTFS_IMAGE }},if=virtio,format=raw \
            -cpu qemu64,+ssse3,+sse4.1,+sse4.2,+popcnt \
            -vga virtio \
            -device virtio-rng-pci \
            -serial mon:stdio -serial null \
            -net nic \
            -net user,hostfwd=tcp::2222-:22 \
            -nographic \
            -append "console=ttyS0 loglevel=7 root=/dev/vda"
        fi

    - name: Display Dashboard URL
      shell: bash
      run: |
        echo "## [Dashboard URL](https://demo.corefense.io/corefense/dashboard?client_id=${{ secrets.CLIENTID }}&job_id=${{ github.run_id }})"